お気に入り登録ボタンを押したらボタンが非表示になる
RinachanBoard31/clean-storemap-web pull request #14
Opened 2024-11-24 07:34 UTC by tanakenology

※ clean-storemap-api の [PR#32](https://github.com/RinachanBoard31/clean-storemap-api/pull/32) がマージされてから、レビューをお願いします🙏

### 機能

「お気に入りに登録」ボタンを押すと、動的にボタンが「お気に入り登録済」のテキストに変わります。

<img width="237" alt="image" src="https://github.com/user-attachments/assets/6351fe2b-0141-4c3a-bbfd-3d1478bf48a4">
<img width="228" alt="image" src="https://github.com/user-attachments/assets/79362ade-b72d-4523-bac9-cefd358ce055">

2024-11-28 19:54 UTC, bluecat101 requested changes
お疲れ様です！一度登録すると再登録できなくするボタンの処理いいですね！
2点ほど対応できていないパターンがあったので確認お願いします。２つ目に関しては、このブランチでない可能性があるのでその際にはfixブランチ等で修正していただけたらなと思います。

### 「店舗情報の取得」を押さないと情報が更新されない
[こちら](https://github.com/RinachanBoard31/clean-storemap-web/pull/14#discussion_r1862599274)で示しているので
ご確認お願いします。

### お店をクリックして閉じて再クリックしても表示されない(影響しているコードがこのブランチの差分に存在しなかったため、このブランチで変更する必要はないかもです。)
以下の手順をした時に表示されないです。
1. お店をクリック
2. 閉じる
3. 他のお店をクリックする前に1で押したお店を再度クリック

https://github.com/RinachanBoard31/clean-storemap-web/blob/de05de34a96837d840d4107b45cd95704c0666b6/src/components/StoreMap.tsx#L24-L26
https://github.com/RinachanBoard31/clean-storemap-web/blob/de05de34a96837d840d4107b45cd95704c0666b6/src/components/StoreMarker.tsx#L91-L93
1つ目のコードでマーカーが押されるたびにマーカーのisActiveの状態がを変更されて、2つ目のコードで各マーカーにおいて"自身の押されているのかの状態(isActive)"が変わると呼び出され表示するかを設定しています。
お店の詳細表示を閉じても、isActiveの状態が変更されずにtrueであり、再度同じお店を押すとisActive = trueなので、変更がなく2つ目のコードが実行されず、表示されないという問題が発生しています。

2024-11-28 19:54 UTC, bluecat101 commented on src/components/StoreDashboard.tsx
> +  const { favoriteStores } = useFavoriteStores(props.userId);
このコードで今登録されているお店の情報を取得していますが、この関数が「店舗情報を取得」を押した時に実行されるため、以下の動作をした時にお気に入り登録済みにならずに登録できる状態になってしまっています。

1. お気に入り登録 
2. 他のお店をクリックする
3. お気に入り登録したお店をクリックする

なので、登録した時にfavoritesStoresを更新するか、お店がクリックされたときに取得するように変更する必要があると思います。

2024-11-30 08:11 UTC, tanakenology commented on src/components/StoreDashboard.tsx
> +  const { favoriteStores } = useFavoriteStores(props.userId);
お店をクリックするたびに取得しても良いのですが、リクエストが増えてしまうので、登録情報を画面側のコンポーネントでも持つようにしました。
具体的には、 StoreMarker コンポーネントで isFavorite ステートを持つようにして、お気に入り登録ボタン押すたびに API リクエストと isFavorite ステートの更新を両方とも行うようにしています。

https://github.com/RinachanBoard31/clean-storemap-web/blob/feat/favorite-store-button/src/components/StoreMarker.tsx#L47-L57

登録情報を持つのは favoriteStores ステートでもできますが、現状の操作では店舗ごとの情報しか更新しないので StoreMarker コンポーネントのステートを使いました。今後、複数店舗を更新する操作が実装された場合は favoriteStores ステートの更新が必要になってくると思います。

2024-11-30 08:21 UTC, tanakenology commented
@bluecat101 
レビューありがとうございます！
ご指摘いただいた以下 2 つのバグを修正しました。
お手数ですが、再度レビューをお願いします🙏

- 「店舗情報の取得」を押さないと情報が更新されない
- お店をクリックして閉じて再クリックしても表示されない

2024-11-30 16:15 UTC, bluecat101 approved these changes
お疲れ様です！修正ありがとうございます。
LGTMです！！

2024-12-03 02:30 UTC, RinachanBoard31 approved these changes
返信がめちゃくちゃ遅くなってしまって申し訳ございません🙇‍♂️
bluecat101さんが指摘してくださった点も完璧に治っていることを確認しました！
目的通りの挙動になっていることをローカルで確認できましたので、Approveさせていただきます！
引き続きよろしくお願いいたします。

2024-12-03 03:14 UTC, merged