サインアップ画面
RinachanBoard31/clean-storemap-web pull request #8
Opened 2024-11-22 10:56 UTC by bluecat101

サインアップ画面を作りました。

手順
1. サインアップ画面にいく
2. googleを用いてサインアップする
3. ユーザ情報を登録する
4. ルートパスに来たらお店を検索する

TODO(別ブランチで行う)
現在、「店舗情報を取得」のボタンがルートパスに存在しているので、その部分を/user等のページでボタンが押せるようにしたいと考えています。

2024-11-22 11:57 UTC, tanakenology requested changes
フォーマットしてくれると嬉しいです！ vscode の拡張機能で「Prettier」をインストールして、以下のように設定すると、ファイル保存と同時にフォーマットされて便利です。
https://github.com/RinachanBoard31/clean-storemap-web/pull/6#issue-2678347895

2024-11-22 12:22 UTC, bluecat101 commented
@tanakenology 
失礼しました。
formatterの方を入れて再度pushしたのでレビューの方お願いします。🙇

2024-11-22 13:01 UTC, tanakenology requested changes
ログイン出来ました！地球が動いてて面白いですね！🌏
いくつかレビューしました。あと、ログイン後のログアウトがうまく出来なかったのですが、 @bluecat101 さんの方ではどうでしょうか？

2024-11-22 13:01 UTC, tanakenology commented on src/App.tsx
>          <Link to="/signup">Signup</Link>
ログイン中は Signup は非表示にしたいです。

2024-11-22 13:01 UTC, tanakenology commented on src/App.tsx
>          </Link>
ログアウト中は Logout は非表示にしたいです。

2024-11-22 13:01 UTC, tanakenology commented on src/api/api.ts
>  }
api.ts からはドメインの情報を分離したいので、メソッド名は sendPutRequest とかにして、リクエストボディは key-value 形式であれば受け取れるようにしたいです。ほとんど同じようになると思いますが、 sendPostRequest が参考になると思います。

2024-11-22 13:12 UTC, bluecat101 commented
@tanakenology 
レビューありがとうございます。
ログアウトに関してはこちらでは動いています。
関係あるかは分かりませんが、バックエンドはmainブランチを使用していて、実行のたびにDBのuserはリセットしています。

https://github.com/user-attachments/assets/ae4f9cc7-f698-494e-8842-8ff857527693

2024-11-22 13:23 UTC, RinachanBoard31 approved these changes
ありがとうございます！
目的通り動作することを確認したので、Approveさせていただきます＞ω＜/
何点かコメントをさせていただきましたので、適宜参照いただければと思います。
重ければ、次回以降のPRで実装する形でも大丈夫です🙇‍♂️
よろしくお願いします！

2024-11-22 13:23 UTC, RinachanBoard31 commented on src/assets/earth.mp4
ありがとうございます！
なんか世界中のmap調べてます感があってカッコよくて好きです😇
周りがhookで色を変えてるのもツボです笑

2024-11-22 13:23 UTC, RinachanBoard31 commented on src/App.tsx
>        navigate("/signup");
こちらにつきまして、シンプルに、`!isAuthenticated()`であるなら認証されていないので`/login`にリダイレクトするという処理ではいかがでしょうか…？
そして、loginページの中に/signupへリダイレクトするリンク（Googleでサインアップするのボタン）があるのがより自然かなと感じました！
もし可能でしたら、デフォルトでリダイレクトされるページも、/signupではなく/loginにしていただけると嬉しいです＞ω＜/

2024-11-22 13:23 UTC, RinachanBoard31 commented on src/App.tsx
> +      navigate("/");
navigate("/")とありますが、rootって/signupじゃなかったでしたっけ…？

2024-11-22 13:23 UTC, RinachanBoard31 commented on src/components/EditUser.tsx
なるほど、updateする形でuser登録するのですね！
今まで作ったapiたちが綺麗に動いて、お気に入り登録までできるのが感動です🥺

2024-11-22 13:23 UTC, RinachanBoard31 commented on src/components/userValidation.ts
こちらの.tsファイルは、/componentsというよりかは/hooksな気がしています🤔

2024-11-22 13:28 UTC, RinachanBoard31 commented
> ログイン出来ました！地球が動いてて面白いですね！🌏 いくつかレビューしました。あと、ログイン後のログアウトがうまく出来なかったのですが、 @bluecat101 さんの方ではどうでしょうか？

私の環境では、@bluecat101 さん同様ログアウトできました👍

2024-11-22 13:38 UTC, bluecat101 commented on src/App.tsx
> +      navigate("/");
ログインしている状態で/signupに飛ぶと再度同じコードが繰り返されてリダイレクトが終わらないため、"/"にしています。

2024-11-22 13:45 UTC, bluecat101 commented on src/App.tsx
>        navigate("/signup");
@RinachanBoard31 
レビューありがとうございます。🙇
おそらく、どのタイミングで`!isAuthenticated()`を実行するのかで変わってくると思いますが、現状のコード(ページが変わるたびに認証を確認する)だと、loginページから/signupページに遷移するときに認証はないのでloginページに再度遷移してしまうと思います。
なので、以下のようなコードだけではうまくいかない気がしますが、確かにあまり綺麗なコードではないので少し探ってみます!
```
 if (!isAuthenticated( )  ) {
      navigate("/login");
}
```
こうゆうコードを想定していた等があれば教えてください！！

2024-11-22 14:49 UTC, bluecat101 commented
@tanakenology 
お疲れ様です。
[こちら](https://github.com/RinachanBoard31/clean-storemap-web/pull/8#pullrequestreview-2454365711)のログアウトがうまくいかないというコメントで、もしかして遷移画面が正しくないということでしょうか？
現状のコードを確認したところ、ログアウトを押した際にクッキーを削除しつつ/に飛ぶという処理が走り、クッキーがないときに/に飛ぶとsignupに遷移しないといけなにも関わらず、/のままという状況でした。🙏
この点に関して[c7b3b38](https://github.com/RinachanBoard31/clean-storemap-web/pull/8/commits/c7b3b3833d8e8954045d22828ce2a4ed966704af)こちらで解消いたしました。

その他の内容についても修正いたしましたので、再度レビューの方お願いします。🙇

2024-11-23 04:51 UTC, tanakenology approved these changes
サインアップ、ログアウトの動作確認しました！
LGTM です！

2024-11-23 04:54 UTC, merged